### ISSUE TITLE
Posible error en la configuración de memoria

### ISSUE THREAD

**Issue by magarvaz** [asi-uniovi/simct#15]
Parece que hay un problema cuando se intenta colocar un módulo de memoria en el último hueco direccionable:

![image](https://github.com/asi-uniovi/simct/assets/131019414/83b3bf72-3b46-42d4-b47e-e54e5fe29fea)

![image](https://github.com/asi-uniovi/simct/assets/131019414/683c526e-7eea-4a9c-8fe9-1fa5c64c7148)

**Comment by jentrialgo** [comment]
En la versión actual no se puede reproducir.
